apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: memos-app
  namespace: argo-cd
spec:
  project: default
  source:
    repoURL: https://github.com/sudo-suadKF/KubeMemos-EKS
    targetRevision: test-db-connect
    path: kubernetes/my-chart
  destination:
    server: https://kubernetes.default.svc
    namespace: production
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
