sources:
  - ingress
  - service

provider:
  name: aws

aws:
  region: eu-west-2
  zoneType: public

serviceAccount:
  create: true
  name: external-dns

domainFilters:
  - sudosuad.co.uk

policy: sync

txtOwnerId: eks-cluster
