reloader:
  enableHA: true
  reloadOnCreate: true
  syncAfterRestart: true
  reloadStrategy: annotations
  readOnlyRootFileSystem: true
  watchGlobally: true
  podMonitor:
    enabled: true
    labels:
      release: prometheus-grafana
  logLevel: debug
  logFormat: json
  deployment:
    replicas: 2
    resources:
      requests:
        cpu: 10m
        memory: 128Mi
      limits:
        cpu: 150m
        memory: 512Mi