apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.deployment.name }}-deployment
  annotations:
    secret.reloader.stakater.com/reload: "memos-dsn"
  labels:
    app: {{ .Values.deployment.name }}
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.deployment.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.deployment.name }}
    spec:
      containers:
      - name: {{ .Values.deployment.name }}
        image: {{ .Values.deployment.image }}:{{ .Values.deployment.tag }}
        env:
          - name: MEMOS_DRIVER
            value: "postgres"

          - name: MEMOS_DSN
            valueFrom:
              secretKeyRef:
                name: memos-dsn
                key: MEMOS_DSN
        ports:
        - containerPort: 8081
        resources:
          limits:
            memory: 512Mi
            cpu: "1"
          requests:
            memory: 256Mi
            cpu: "0.2"
