apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-dsn
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: memos-dsn
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        MEMOS_DSN: "postgres://{{ `{{ .username | urlquery }}` }}:{{ `{{ .password | urlquery }}` }}@production-rds.c7ueomi6yzcn.eu-west-2.rds.amazonaws.com:5432/postgresrds?sslmode=require"
  data:
  - secretKey: username
    remoteRef:
      key: arn:aws:secretsmanager:eu-west-2:541064517911:secret:rds!db-590365b6-668b-4f1b-bbdd-0792b74b0972-pBDHBi
      property: username
  - secretKey: password
    remoteRef:
      key: arn:aws:secretsmanager:eu-west-2:541064517911:secret:rds!db-590365b6-668b-4f1b-bbdd-0792b74b0972-pBDHBi
      property: password
