apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: memos-dsn
  namespace: external-secrets
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: memos-dsn
    creationPolicy: Owner
    template:
      metadata:
        annotations:
          reloader.stakater.com/match: "true"
      engineVersion: v2
      data:
        MEMOS_DSN: "postgres://{{ `{{ .username }}` }}:{{ `{{ .password | urlquery }}` }}@{{ `{{ .host }}` }}:{{ `{{ .port }}` }}/{{ `{{ .dbname }}` }}?sslmode=require"
  data:
  - secretKey: username
    remoteRef:
      key: arn:aws:secretsmanager:eu-west-2:541064517911:secret:production/rds/credentials-7k3lb5
      property: username
  - secretKey: password
    remoteRef:
      key: arn:aws:secretsmanager:eu-west-2:541064517911:secret:production/rds/credentials-7k3lb5
      property: password
  - secretKey: host
    remoteRef:
      key: arn:aws:secretsmanager:eu-west-2:541064517911:secret:production/rds/credentials-7k3lb5
      property: host
  - secretKey: port
    remoteRef:
      key: arn:aws:secretsmanager:eu-west-2:541064517911:secret:production/rds/credentials-7k3lb5
      property: port
  - secretKey: dbname
    remoteRef:
      key: arn:aws:secretsmanager:eu-west-2:541064517911:secret:production/rds/credentials-7k3lb5
      property: dbname
