repositories:
  - name: traefik
    url: https://traefik.github.io/charts

  - name: external-dns
    url: https://kubernetes-sigs.github.io/external-dns/

  - name: cert-manager
    url: https://charts.jetstack.io

  - name: argo-cd
    url: https://argoproj.github.io/argo-helm

releases:
  - name: traefik
    chart: traefik/traefik
    namespace: traefik
    createNamespace: true
    values:
    - helm-values/traefik.yaml

  - name: external-dns
    chart: external-dns/external-dns
    namespace: external-dns
    createNamespace: true
    values:
      - helm-values/external-dns.yaml
    needs:
      - traefik/traefik

  - name: cert-manager
    chart: cert-manager/cert-manager
    namespace: cert-manager
    createNamespace: true
    values:
      - installCRDs: true

  - name: argo-cd
    chart: argo-cd/argo-cd
    namespace: argo-cd
    createNamespace: true
    values:
      - server:
          extraArgs:
            - --insecure
