name: K8s Dispatch

on:
  workflow_dispatch:
    inputs:
      action:
        description: "Choose 'Deploy' or 'Undeploy' K8s"
        required: true
        type: choice
        options:
          - Deploy
          - Undeploy
        default: 'Deploy'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-2
  CLUSTER_NAME: my-eks-cluster
  K8s_DIR: ./kubernetes
  ARGO_CD_DIR: ./argo-cd
  MONITORING_DIR: ./monitoring
  PROMETHEUS_DIR: ./monitoring/prometheus
  GRAFANA_DIR: ./monitoring/grafana

jobs:
  deploy:
    name: Deploy K8s
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'Deploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.K8s_DIR }}
    steps:
      - name: Check Correct Input
        run: |
          if [ "${{ github.event.inputs.action }}" != "Deploy" ]; then
            echo "Deploy cancelled"
            exit 1
          fi
        working-directory: .

      - uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v5
        with:
          version: 'latest'

      - name: Set Up Helm
        uses: azure/setup-helm@v5
        with:
          version: 'latest'

      - name: Set Up Helm-diff
        run: helm plugin install https://github.com/databus23/helm-diff --verify=false

      - name: Cache Helm
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/helm
            ~/.config/helm
            ~/.local/share/helm/plugins
          key: ${{ runner.os }}-helm-${{ hashFiles('helmfile.yaml', 'helm-values/*.yaml') }}
          restore-keys: |
            ${{ runner.os }}-helm-

      - name: Set Up Helmfile
        run: |
          curl -LO https://github.com/helmfile/helmfile/releases/download/v1.5.5/helmfile_1.5.5_linux_amd64.tar.gz
          tar xzf helmfile_1.5.5_linux_amd64.tar.gz
          sudo mv helmfile /usr/local/bin/

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Check if Production Exists
        id: check
        run: |
          if kubectl get ns production; then
            echo "exists=true" >> "$GITHUB_OUTPUT"
          else
            echo "exists=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Exit Pipeline
        if: steps.check.outputs.exists == 'true'
        run: exit 1

      - name: Apply Helmfile
        if: steps.check.outputs.exists == 'false'
        run: helmfile apply

      - name: Wait for Cert Manager & Traefik are Available
        run: |
          kubectl wait --for=condition=Available deployment/cert-manager -n cert-manager --timeout=180s
          kubectl wait --for=condition=Available deployment/cert-manager-webhook -n cert-manager --timeout=180s
          kubectl wait --for=condition=Available deployment/cert-manager-cainjector -n cert-manager --timeout=180s
          kubectl wait --for=condition=Available deployment/traefik -n traefik --timeout=180s

      - name: Apply Cluster Issuer
        if: steps.check.outputs.exists == 'false'
        run: kubectl apply -f cluster-issuer.yaml

      - name: Apply ArgoCD
        if: steps.check.outputs.exists == 'false'
        run: |
          kubectl apply -f ${{ env.ARGO_CD_DIR}}/argo-cd.yaml
          kubectl apply -f ${{ env.ARGO_CD_DIR}}/ingress-http.yaml
          kubectl apply -f ${{ env.ARGO_CD_DIR}}/ingress-https.yaml
          kubectl apply -f ${{ env.ARGO_CD_DIR}}/middleware.yaml

      - name: Apply Monitoring
        if: steps.check.outputs.exists == 'false'
        run: |
          kubectl apply -f ${{ env.GRAFANA_DIR }}/ingress-http.yaml
          kubectl apply -f ${{ env.GRAFANA_DIR }}/ingress-https.yaml
          kubectl apply -f ${{ env.PROMETHEUS_DIR }}/ingress-http.yaml
          kubectl apply -f ${{ env.PROMETHEUS_DIR }}/ingress-https.yaml
          kubectl apply -f ${{ env.MONITORING_DIR }}/middleware.yaml

  Undeploy:
    name: Undeploy K8s
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.action == 'Undeploy'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.K8s_DIR }}
    steps:
      - name: Check Correct Input
        run: |
          if [ "${{ github.event.inputs.action }}" != "Undeploy" ]; then
            echo "Undeploy cancelled"
            exit 1
          fi
        working-directory: .

      - uses: actions/checkout@v6

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Set Up Kubectl
        uses: azure/setup-kubectl@v5
        with:
          version: 'latest'

      - name: Set Up Helm
        uses: azure/setup-helm@v5
        with:
          version: 'latest'

      - name: Set Up Helm-diff
        run: helm plugin install https://github.com/databus23/helm-diff --verify=false

      - name: Set Up Helmfile
        run: |
          curl -LO https://github.com/helmfile/helmfile/releases/download/v1.5.5/helmfile_1.5.5_linux_amd64.tar.gz
          tar xzf helmfile_1.5.5_linux_amd64.tar.gz
          sudo mv helmfile /usr/local/bin/

      - name: Update Kubeconfig
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.CLUSTER_NAME }}

      - name: Delete Cluster Issuer
        run: kubectl delete clusterissuer letsencrypt-https -n certmanager --ignore-not-found

      - name: Delete ArgoCD
        run: |
          kubectl delete application memos-app -n argo-cd --ignore-not-found
          kubectl delete middleware -n argo-cd redirectscheme --ignore-not-found
          kubectl delete ingress -n argo-cd argo-cd-ingress-https --ignore-not-found
          kubectl delete ingress -n argo-cd argo-cd-ingress-http --ignore-not-found

      - name: Delete Production
        run: |
          kubectl delete deploy memos-deployment -n production --ignore-not-found
          kubectl delete svc memos-service -n production --ignore-not-found
          kubectl delete clustersecretstore aws-secrets -n production --ignore-not-found
          kubectl delete secret memos-dsn -n production --ignore-not-found
          kubectl delete externalsecrets memos-dsn -n production --ignore-not-found
          kubectl delete ingress memos-ingress-http -n production --ignore-not-found
          kubectl delete ingress memos-ingress-https -n production --ignore-not-found
          kubectl delete middleware redirectscheme -n production --ignore-not-found

      - name: Delete Monitoring
        run: |
          kubectl delete middleware -n monitoring redirectscheme --ignore-not-found
          kubectl delete ingress -n monitoring prometheus-ingress-https --ignore-not-found
          kubectl delete ingress -n monitoring prometheus-ingress-http --ignore-not-found
          kubectl delete ingress -n monitoring grafana-ingress-https --ignore-not-found
          kubectl delete ingress -n monitoring grafana-ingress-http --ignore-not-found

      - name: Delete Namespaces
        run: |
          kubectl delete ns external-dns --ignore-not-found
          kubectl delete ns external-secrets --ignore-not-found
          kubectl delete ns monitoring --ignore-not-found
          kubectl delete ns stakater-reloader --ignore-not-found
          kubectl delete ns traefik --ignore-not-found
          kubectl delete ns argo-cd --ignore-not-found
          kubectl delete ns cert-manager --ignore-not-found
          kubectl delete ns production --ignore-not-found

      - name: Destroy Helmfile
        run: helmfile destroy
